/*
 * Interface wrapper code.
 *
 * Generated by SIP 4.18
 *
 * Copyright (c) 2014 Riverbank Computing Limited <info@riverbankcomputing.com>
 * 
 * This file is part of PyQt.
 * 
 * This file may be used under the terms of the GNU General Public
 * License versions 2.0 or 3.0 as published by the Free Software
 * Foundation and appearing in the files LICENSE.GPL2 and LICENSE.GPL3
 * included in the packaging of this file.  Alternatively you may (at
 * your option) use any later version of the GNU General Public
 * License if such license has been publicly approved by Riverbank
 * Computing Limited (or its successors, if any) and the KDE Free Qt
 * Foundation. In addition, as a special exception, Riverbank gives you
 * certain additional rights. These rights are described in the Riverbank
 * GPL Exception version 1.1, which can be found in the file
 * GPL_EXCEPTION.txt in this package.
 * 
 * If you are unsure which license is appropriate for your use, please
 * contact the sales department at sales@riverbankcomputing.com.
 * 
 * This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
 * WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 */

#include "sipAPIQtXml.h"

#line 198 "/media/dhankar/Dhankar_1/a1_18/a1_______QGIS/sip/QtXml/qdom.sip"
#include <qdom.h>
#line 34 "/media/dhankar/Dhankar_1/a1_18/a1_______QGIS/QtXml/sipQtXmlQDomDocumentType.cpp"

#line 62 "/media/dhankar/Dhankar_1/a1_18/a1_______QGIS/sip/QtXml/qdom.sip"
#include <qdom.h>
#line 38 "/media/dhankar/Dhankar_1/a1_18/a1_______QGIS/QtXml/sipQtXmlQDomDocumentType.cpp"
#line 36 "sip/QtCore/qstring.sip"
#include <qstring.h>
#line 41 "/media/dhankar/Dhankar_1/a1_18/a1_______QGIS/QtXml/sipQtXmlQDomDocumentType.cpp"
#line 260 "/media/dhankar/Dhankar_1/a1_18/a1_______QGIS/sip/QtXml/qdom.sip"
#include <qdom.h>
#line 44 "/media/dhankar/Dhankar_1/a1_18/a1_______QGIS/QtXml/sipQtXmlQDomDocumentType.cpp"
#line 35 "sip/QtCore/qtextstream.sip"
#include <qtextstream.h>
#line 47 "/media/dhankar/Dhankar_1/a1_18/a1_______QGIS/QtXml/sipQtXmlQDomDocumentType.cpp"
#line 345 "/media/dhankar/Dhankar_1/a1_18/a1_______QGIS/sip/QtXml/qdom.sip"
#include <qdom.h>
#line 50 "/media/dhankar/Dhankar_1/a1_18/a1_______QGIS/QtXml/sipQtXmlQDomDocumentType.cpp"
#line 397 "/media/dhankar/Dhankar_1/a1_18/a1_______QGIS/sip/QtXml/qdom.sip"
#include <qdom.h>
#line 53 "/media/dhankar/Dhankar_1/a1_18/a1_______QGIS/QtXml/sipQtXmlQDomDocumentType.cpp"
#line 303 "/media/dhankar/Dhankar_1/a1_18/a1_______QGIS/sip/QtXml/qdom.sip"
#include <qdom.h>
#line 56 "/media/dhankar/Dhankar_1/a1_18/a1_______QGIS/QtXml/sipQtXmlQDomDocumentType.cpp"
#line 462 "/media/dhankar/Dhankar_1/a1_18/a1_______QGIS/sip/QtXml/qdom.sip"
#include <qdom.h>
#line 59 "/media/dhankar/Dhankar_1/a1_18/a1_______QGIS/QtXml/sipQtXmlQDomDocumentType.cpp"
#line 421 "/media/dhankar/Dhankar_1/a1_18/a1_______QGIS/sip/QtXml/qdom.sip"
#include <qdom.h>
#line 62 "/media/dhankar/Dhankar_1/a1_18/a1_______QGIS/QtXml/sipQtXmlQDomDocumentType.cpp"
#line 435 "/media/dhankar/Dhankar_1/a1_18/a1_______QGIS/sip/QtXml/qdom.sip"
#include <qdom.h>
#line 65 "/media/dhankar/Dhankar_1/a1_18/a1_______QGIS/QtXml/sipQtXmlQDomDocumentType.cpp"
#line 384 "/media/dhankar/Dhankar_1/a1_18/a1_______QGIS/sip/QtXml/qdom.sip"
#include <qdom.h>
#line 68 "/media/dhankar/Dhankar_1/a1_18/a1_______QGIS/QtXml/sipQtXmlQDomDocumentType.cpp"
#line 450 "/media/dhankar/Dhankar_1/a1_18/a1_______QGIS/sip/QtXml/qdom.sip"
#include <qdom.h>
#line 71 "/media/dhankar/Dhankar_1/a1_18/a1_______QGIS/QtXml/sipQtXmlQDomDocumentType.cpp"
#line 216 "/media/dhankar/Dhankar_1/a1_18/a1_______QGIS/sip/QtXml/qdom.sip"
#include <qdom.h>
#line 74 "/media/dhankar/Dhankar_1/a1_18/a1_______QGIS/QtXml/sipQtXmlQDomDocumentType.cpp"
#line 291 "/media/dhankar/Dhankar_1/a1_18/a1_______QGIS/sip/QtXml/qdom.sip"
#include <qdom.h>
#line 77 "/media/dhankar/Dhankar_1/a1_18/a1_______QGIS/QtXml/sipQtXmlQDomDocumentType.cpp"
#line 409 "/media/dhankar/Dhankar_1/a1_18/a1_______QGIS/sip/QtXml/qdom.sip"
#include <qdom.h>
#line 80 "/media/dhankar/Dhankar_1/a1_18/a1_______QGIS/QtXml/sipQtXmlQDomDocumentType.cpp"
#line 328 "/media/dhankar/Dhankar_1/a1_18/a1_______QGIS/sip/QtXml/qdom.sip"
#include <qdom.h>
#line 83 "/media/dhankar/Dhankar_1/a1_18/a1_______QGIS/QtXml/sipQtXmlQDomDocumentType.cpp"
#line 173 "/media/dhankar/Dhankar_1/a1_18/a1_______QGIS/sip/QtXml/qdom.sip"
#include <qdom.h>
#line 86 "/media/dhankar/Dhankar_1/a1_18/a1_______QGIS/QtXml/sipQtXmlQDomDocumentType.cpp"


PyDoc_STRVAR(doc_QDomDocumentType_name, "name(self) -> QString");

extern "C" {static PyObject *meth_QDomDocumentType_name(PyObject *, PyObject *);}
static PyObject *meth_QDomDocumentType_name(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const QDomDocumentType *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QDomDocumentType, &sipCpp))
        {
            QString*sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = new QString(sipCpp->name());
            Py_END_ALLOW_THREADS

            return sipConvertFromNewType(sipRes,sipType_QString,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QDomDocumentType, sipName_name, doc_QDomDocumentType_name);

    return NULL;
}


PyDoc_STRVAR(doc_QDomDocumentType_entities, "entities(self) -> QDomNamedNodeMap");

extern "C" {static PyObject *meth_QDomDocumentType_entities(PyObject *, PyObject *);}
static PyObject *meth_QDomDocumentType_entities(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const QDomDocumentType *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QDomDocumentType, &sipCpp))
        {
            QDomNamedNodeMap*sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = new QDomNamedNodeMap(sipCpp->entities());
            Py_END_ALLOW_THREADS

            return sipConvertFromNewType(sipRes,sipType_QDomNamedNodeMap,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QDomDocumentType, sipName_entities, doc_QDomDocumentType_entities);

    return NULL;
}


PyDoc_STRVAR(doc_QDomDocumentType_notations, "notations(self) -> QDomNamedNodeMap");

extern "C" {static PyObject *meth_QDomDocumentType_notations(PyObject *, PyObject *);}
static PyObject *meth_QDomDocumentType_notations(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const QDomDocumentType *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QDomDocumentType, &sipCpp))
        {
            QDomNamedNodeMap*sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = new QDomNamedNodeMap(sipCpp->notations());
            Py_END_ALLOW_THREADS

            return sipConvertFromNewType(sipRes,sipType_QDomNamedNodeMap,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QDomDocumentType, sipName_notations, doc_QDomDocumentType_notations);

    return NULL;
}


PyDoc_STRVAR(doc_QDomDocumentType_publicId, "publicId(self) -> QString");

extern "C" {static PyObject *meth_QDomDocumentType_publicId(PyObject *, PyObject *);}
static PyObject *meth_QDomDocumentType_publicId(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const QDomDocumentType *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QDomDocumentType, &sipCpp))
        {
            QString*sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = new QString(sipCpp->publicId());
            Py_END_ALLOW_THREADS

            return sipConvertFromNewType(sipRes,sipType_QString,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QDomDocumentType, sipName_publicId, doc_QDomDocumentType_publicId);

    return NULL;
}


PyDoc_STRVAR(doc_QDomDocumentType_systemId, "systemId(self) -> QString");

extern "C" {static PyObject *meth_QDomDocumentType_systemId(PyObject *, PyObject *);}
static PyObject *meth_QDomDocumentType_systemId(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const QDomDocumentType *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QDomDocumentType, &sipCpp))
        {
            QString*sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = new QString(sipCpp->systemId());
            Py_END_ALLOW_THREADS

            return sipConvertFromNewType(sipRes,sipType_QString,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QDomDocumentType, sipName_systemId, doc_QDomDocumentType_systemId);

    return NULL;
}


PyDoc_STRVAR(doc_QDomDocumentType_internalSubset, "internalSubset(self) -> QString");

extern "C" {static PyObject *meth_QDomDocumentType_internalSubset(PyObject *, PyObject *);}
static PyObject *meth_QDomDocumentType_internalSubset(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const QDomDocumentType *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QDomDocumentType, &sipCpp))
        {
            QString*sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = new QString(sipCpp->internalSubset());
            Py_END_ALLOW_THREADS

            return sipConvertFromNewType(sipRes,sipType_QString,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QDomDocumentType, sipName_internalSubset, doc_QDomDocumentType_internalSubset);

    return NULL;
}


PyDoc_STRVAR(doc_QDomDocumentType_nodeType, "nodeType(self) -> QDomNode.NodeType");

extern "C" {static PyObject *meth_QDomDocumentType_nodeType(PyObject *, PyObject *);}
static PyObject *meth_QDomDocumentType_nodeType(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const QDomDocumentType *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QDomDocumentType, &sipCpp))
        {
            QDomNode::NodeType sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = sipCpp->nodeType();
            Py_END_ALLOW_THREADS

            return sipConvertFromEnum(sipRes,sipType_QDomNode_NodeType);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QDomDocumentType, sipName_nodeType, doc_QDomDocumentType_nodeType);

    return NULL;
}


/* Call the instance's destructor. */
extern "C" {static void release_QDomDocumentType(void *, int);}
static void release_QDomDocumentType(void *sipCppV,int)
{
    Py_BEGIN_ALLOW_THREADS

    delete reinterpret_cast<QDomDocumentType *>(sipCppV);

    Py_END_ALLOW_THREADS
}


extern "C" {static void assign_QDomDocumentType(void *, SIP_SSIZE_T, const void *);}
static void assign_QDomDocumentType(void *sipDst, SIP_SSIZE_T sipDstIdx, const void *sipSrc)
{
    reinterpret_cast<QDomDocumentType *>(sipDst)[sipDstIdx] = *reinterpret_cast<const QDomDocumentType *>(sipSrc);
}


extern "C" {static void *array_QDomDocumentType(SIP_SSIZE_T);}
static void *array_QDomDocumentType(SIP_SSIZE_T sipNrElem)
{
    return new QDomDocumentType[sipNrElem];
}


extern "C" {static void *copy_QDomDocumentType(const void *, SIP_SSIZE_T);}
static void *copy_QDomDocumentType(const void *sipSrc, SIP_SSIZE_T sipSrcIdx)
{
    return new QDomDocumentType(reinterpret_cast<const QDomDocumentType *>(sipSrc)[sipSrcIdx]);
}


extern "C" {static void dealloc_QDomDocumentType(sipSimpleWrapper *);}
static void dealloc_QDomDocumentType(sipSimpleWrapper *sipSelf)
{
    if (sipIsPyOwned(sipSelf))
    {
        release_QDomDocumentType(sipGetAddress(sipSelf),0);
    }
}


extern "C" {static void *init_type_QDomDocumentType(sipSimpleWrapper *, PyObject *, PyObject *, PyObject **, PyObject **, PyObject **);}
static void *init_type_QDomDocumentType(sipSimpleWrapper *, PyObject *sipArgs, PyObject *sipKwds, PyObject **sipUnused, PyObject **, PyObject **sipParseErr)
{
    QDomDocumentType *sipCpp = 0;

    {
        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, NULL, sipUnused, ""))
        {
            Py_BEGIN_ALLOW_THREADS
            sipCpp = new QDomDocumentType();
            Py_END_ALLOW_THREADS

            return sipCpp;
        }
    }

    {
        const QDomDocumentType* a0;

        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, NULL, sipUnused, "J9", sipType_QDomDocumentType, &a0))
        {
            Py_BEGIN_ALLOW_THREADS
            sipCpp = new QDomDocumentType(*a0);
            Py_END_ALLOW_THREADS

            return sipCpp;
        }
    }

    return NULL;
}


/* Define this type's super-types. */
static sipEncodedTypeDef supers_QDomDocumentType[] = {{13, 255, 1}};


static PyMethodDef methods_QDomDocumentType[] = {
    {SIP_MLNAME_CAST(sipName_entities), meth_QDomDocumentType_entities, METH_VARARGS, SIP_MLDOC_CAST(doc_QDomDocumentType_entities)},
    {SIP_MLNAME_CAST(sipName_internalSubset), meth_QDomDocumentType_internalSubset, METH_VARARGS, SIP_MLDOC_CAST(doc_QDomDocumentType_internalSubset)},
    {SIP_MLNAME_CAST(sipName_name), meth_QDomDocumentType_name, METH_VARARGS, SIP_MLDOC_CAST(doc_QDomDocumentType_name)},
    {SIP_MLNAME_CAST(sipName_nodeType), meth_QDomDocumentType_nodeType, METH_VARARGS, SIP_MLDOC_CAST(doc_QDomDocumentType_nodeType)},
    {SIP_MLNAME_CAST(sipName_notations), meth_QDomDocumentType_notations, METH_VARARGS, SIP_MLDOC_CAST(doc_QDomDocumentType_notations)},
    {SIP_MLNAME_CAST(sipName_publicId), meth_QDomDocumentType_publicId, METH_VARARGS, SIP_MLDOC_CAST(doc_QDomDocumentType_publicId)},
    {SIP_MLNAME_CAST(sipName_systemId), meth_QDomDocumentType_systemId, METH_VARARGS, SIP_MLDOC_CAST(doc_QDomDocumentType_systemId)}
};

PyDoc_STRVAR(doc_QDomDocumentType, "\1QDomDocumentType()\n"
    "QDomDocumentType(QDomDocumentType)");


pyqt4ClassTypeDef sipTypeDef_QtXml_QDomDocumentType = {
{
    {
        -1,
        0,
        0,
        SIP_TYPE_CLASS,
        sipNameNr_QDomDocumentType,
        {0}
    },
    {
        sipNameNr_QDomDocumentType,
        {0, 0, 1},
        7, methods_QDomDocumentType,
        0, 0,
        0, 0,
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    },
    doc_QDomDocumentType,
    -1,
    -1,
    supers_QDomDocumentType,
    0,
    init_type_QDomDocumentType,
    0,
    0,
#if PY_MAJOR_VERSION >= 3
    0,
    0,
#else
    0,
    0,
    0,
    0,
#endif
    dealloc_QDomDocumentType,
    assign_QDomDocumentType,
    array_QDomDocumentType,
    copy_QDomDocumentType,
    release_QDomDocumentType,
    0,
    0,
    0,
    0,
    0,
    0,
    0
},
    0,
    0,
    0
};
